"use client";

import { useState, useEffect } from "react";

export default function DisclaimerGate({ children }: { children: React.ReactNode }) {
  const [accepted, setAccepted] = useState(false);
  const [checked, setChecked] = useState(false);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("disclaimerAccepted");
    if (saved === "true") {
      setAccepted(true);
    }
    setReady(true);
  }, []);

  const handleAccept = () => {
    if (checked) {
      localStorage.setItem("disclaimerAccepted", "true");
      setAccepted(true);
    }
  };

  if (!ready) return null;

  if (!accepted) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
        <div className="bg-[#F6F4EF] max-w-2xl w-full max-h-[80vh] overflow-y-auto rounded-lg p-6 shadow-xl">
          <h2 className="text-xl font-bold text-[#16241D] mb-4">
            Important Legal Notice
          </h2>
          <pre className="whitespace-pre-wrap text-sm text-[#16241D] font-sans leading-relaxed">
{`APPLICATION DISCLAIMER

CRITICAL LEGAL NOTICE, LEGAL DISCLAIMER & DATA PRIVACY AGREEMENT

IMPORTANT: BY ACCESSING OR USING THIS APPLICATION, YOU EXPLICITLY AGREE TO BE BOUND BY ALL THE TERMS AND CONDITIONS STATED BELOW. IF YOU DO NOT AGREE, YOU MUST IMMEDIATELY CEASE AND TERMINATE ANY USE OF THIS PLATFORM.

1. ABSOLUTE DATA PRIVACY & ENCRYPTION GUARANTEE (NO HUMAN FACTOR)
All private numbers, financial offers, maximum budgets, and minimum acceptable prices entered into this system are strictly LOCKED, FULLY ENCRYPTED, and processed automatically by an un-monitored AI algorithm.

NO HUMAN BEING — including the creator of this application, the administrators, the owners of the "Grandma Does AI" YouTube channel, or any third party — has the technical ability or legal authorization to view, access, inspect, or manipulate individual private numbers. The application functions blindly and outputs only the automated final match (ZOPA - Zone of Possible Agreement).

2. NOT A LICENSED REAL ESTATE BROKER OR AGENT
This application, its creators, operators, owners, and affiliates are NOT licensed real estate brokers, salespersons, agents, or attorneys within the State of Washington, the State of Oregon, or anywhere within the United States of America.

This platform does NOT perform any licensed real estate activities. We do not solicit listings, represent buyers, represent sellers, manage properties, conduct formal appraisals, or handle escrow funds.

3. NO REPRESENTATION & NO FIDUCIARY DUTY
This platform operates strictly as an independent, mathematical, and analytical matching tool. We do not represent any party in any current, past, or future real estate transactions. No agency relationship, brokerage relationship, or fiduciary duty is created or implied between the user and this platform or its creators. Any relationship, communication, or contract established between users outside or inside this application is entirely their own responsibility.

4. SCOPE OF SERVICE & INFORMATIONAL PURPOSE ONLY
This application is currently optimized strictly for the Pacific Northwest (NW) region (including WA/OR), serving as a pre-negotiation and pre-offer filter. All data, links to public county permit records, utility estimates, noise levels, and price match indications (ZOPA) generated by this tool are purely informational, statistical, and educational. They do not constitute formal real estate appraisals, binding evaluations, legal advice, or financial advice. Users are strictly advised to consult with their own licensed real estate attorneys and brokers before signing any binding contracts.

5. AUTOMATED DOCUMENTS & NO BINDING CONTRACTS
Any text outputs, summaries, or matches generated by this application do NOT constitute a legally binding real estate Purchase and Sale Agreement. If the parties agree on a ZOPA matching price, this tool may only assist in generating a non-binding "Letter of Intent" (LOI) or "Memorandum of Understanding" (MOU). It is the sole responsibility of the users to deliver such documents to their attorneys or licensed brokers for formal, legally compliant drafting.

6. TOTAL EXCLUSION OF LIABILITY & INDEMNIFICATION
The user assumes 100% of the risk and liability for any actions, investments, or negotiations made based on the data provided by this tool. Under no circumstances shall the creator ("Grandma Does AI"), administrators, or software owners be liable for any financial losses, failed real estate transactions, legal disputes, property damages, or emotional distress arising out of or related to the use of this application. By checking "I Accept", you permanently release the platform and its creators from any and all legal, criminal, and financial liability — PERIOD.`}
          </pre>

          <label className="flex items-start gap-2 mt-4 text-sm text-[#16241D]">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-1"
            />
            I have read and agree to the above terms.
          </label>

          <button
            onClick={handleAccept}
            disabled={!checked}
            className="mt-4 w-full py-3 rounded-md font-semibold text-white bg-[#3F5C4C] disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            I Accept
          </button>
        </div>
      </div>
    );
  }

  return <>{children}</>;
}
